name: Build Release

# Controls when the action will run.  
on:
  push:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "buildRelease"
  buildRelease:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Add permission to execute gradlew
        run: chmod +x ./gradlew

      - name: Clean
        run: ./gradlew clean

      # Build the release apk
      - name: Build the app
        run: ./gradlew assembleRelease

      - name: Add permission to execute zipalign
        run: chmod +x ./tools/zipalign.exe

      # Verify the release apk alignment
      - name: Verify apk alignment
        run: ./tools/zipalign.exe -c -v -p 4 app/build/outputs/apk/release/app-release-unsigned.apk

      # Upload release artifact
      - uses: actions/upload-artifact@v2
        with:
          name: app-release-unsigned.apk
          path: app/build/outputs/apk/release/

